"""Build runtime metadata and collision silhouette from the approved cutouts."""
from pathlib import Path
import json,base64
import numpy as np
import cv2
from PIL import Image
root=Path(__file__).resolve().parents[1]
assert Path.cwd().resolve()==root
art=root/'public/ship-art'
m=json.loads((art/'manifest.json').read_text(encoding='utf-8'))
for s in m['sailSets']:
    for p in s['sails']:
        a=np.array(Image.open(art/p['cloth']))[:,:,3]
        contours,_=cv2.findContours((a>128).astype('uint8'),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
        p['outline']=cv2.approxPolyDP(max(contours,key=cv2.contourArea),2,True)[:,0,:].tolist()
data={k:m[k] for k in ['hulls','sailSets','flags','masts']}
(root/'src/ship-art-data.js').write_text('// Generated by scripts/build-ship-art-data.py from supplied PNGs.\nexport const SHIP_ART='+json.dumps(data,separators=(',',':'))+';\n',encoding='utf-8')
a=np.array(Image.open(art/'bodies/IMG_7285-right.png'))[:,:,3]
y,x=np.indices((320,512));wx=-1.4+(x+.5)*2.8/512;wy=-.8+(y+.5)*1.6/320
sx=np.rint(810+wx*480).astype(int);sy=np.rint(960-(wy+.56)*480).astype(int)
inside=(sx>=0)&(sx<1792)&(sy>=0)&(sy<978)
mask=np.zeros((320,512),dtype='uint8');mask[inside]=(a[sy[inside],sx[inside]]>160)
bits=base64.b64encode(np.packbits(mask.ravel(),bitorder='little')).decode()
(root/'src/ship-art-mask.js').write_text('// Generated from the base hull alpha; same world registration as the renderer.\nexport const ART_HULL_BITS='+json.dumps(bits)+';\n',encoding='utf-8')
print('Built runtime art metadata and hull collision mask.')
