import * as M from './model.js';
const {$=null}= {};
const el=id=>document.getElementById(id),fmt=n=>Math.floor(n).toLocaleString(),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='pirate-clashers-v1';let state,saveError='',page='battle',tab='ship',selected=null,gunner=null,target='hull',port=0,busy=false,scope=false,toastTimer,lastFocus;
try{state=M.restore(localStorage.getItem(KEY));}catch(e){state=M.fresh();saveError='Your previous save could not be read. It has been preserved; use Settings to export it before starting a new save.';}
port=state.port;
function save(){if(saveError)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){saveError='Progress could not be saved on this browser. Export your captain in Settings.';toast(saveError);}}
function toast(s){el('toast').textContent=s;el('toast').classList.add('toast-show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el('toast').classList.remove('toast-show'),3500);}
function button(label,action,id='',cls='',disabled=false){return '<button class="'+cls+'" data-action="'+action+'" data-id="'+esc(id)+'" '+(disabled?'disabled':'')+'>'+label+'</button>';}
function title(k,h,p=''){return '<div class="page-title"><div><div class="eyebrow">'+k+'</div><h2>'+h+'</h2></div><p>'+p+'</p></div>';}
function modal(html){lastFocus=document.activeElement;el('sheet').innerHTML=button('×','close','','close')+html;if(!el('sheet').open)el('sheet').showModal();}
function close(){el('sheet').close();lastFocus?.focus?.();}
el('sheet').addEventListener('close',()=>lastFocus?.focus?.());
function pirate(id){return M.PIRATES.find(p=>p.id===Number(id));}
function art(p,cls='pirate-art'){if(p.id>=1&&p.id<=36)return '<img class="'+cls+'" src="/Pirate%20Art/pirate_segments/zombie-pirate/zombie-pirate-'+p.id+'.png" alt="'+esc(p.name)+'">';return '<div class="pirate-icon">'+p.icon+'</div>';}
function cost(c){return Object.entries(c).map(([k,v])=>({gold:'🪙',gems:'💎',wood:'🪵',metal:'⚙',cloth:'▱'}[k]||'')+' '+fmt(v)+' '+k).join(' · ');}
function materials(){return '<div class="materials">'+Object.entries(state.mats).map(([k,v])=>'<div class="material">'+cost({[k]:v})+'</div>').join('')+'</div>';}
function shell(){document.body.classList.toggle('reduce-motion',!state.settings.motion);document.body.classList.toggle('battle-mode',page==='arena');el('rail').innerHTML='<div class="brand">⚓<small>PIRATE<br>CLASHERS</small></div>'+[['battle','⚔','Battle'],['crew','♟','Crew'],['ports','◎','Ports'],['booty','▤','Booty'],['store','◇','Store']].map(([k,i,n])=>'<button class="nav-btn '+(page===k?'active':'')+'" data-action="nav" data-id="'+k+'" aria-label="'+n+'" '+(page===k?'aria-current="page"':'')+'><span class="icon">'+i+'</span>'+n+'</button>').join('')+'<div class="rail-bottom">'+button('⚙<br><small>Settings</small>','nav','settings','nav-btn')+'<div class="version">LOCAL VOYAGE</div></div>';el('topbar').innerHTML='<div class="crumb">PIRATE CLASHERS <span style="opacity:.45"> / </span> '+esc(page)+'</div><div class="wallet"><span class="currency">🪙 '+fmt(state.gold)+'</span><span class="gem">💎 '+fmt(state.gems)+'</span><span class="pill">⚓ '+M.PORTS[state.port]+'</span></div>';}
function render(){M.advance(state,Date.now());save();shell();const views={battle:home,crew:crew,ports:ports,booty:booty,store:store,settings:settings,arena:arena};el('main').innerHTML=(saveError?'<div class="error-note">'+saveError+'</div>':'')+(views[page]||home)();if(page==='arena')updateArena();for(const f of document.querySelectorAll('iframe'))f.addEventListener('load',()=>{let ready=false;try{ready=!!f.contentDocument?.querySelector('canvas')?.getContext('webgl2');}catch{}if(!ready){f.style.visibility='hidden';const note=document.createElement('div');note.className='render-note';note.textContent=f.id==='enemyShip'?'Ship renderer unavailable. Choose a target and use Fire to continue.':f.id==='playerShip'?'Your ship renderer is unavailable.':'Ocean renderer unavailable.';f.after(note);}});if(page==='booty'){const track=el('track');track.scrollLeft=Math.max(0,(M.seasonLevel(state)-2)*144);track.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();track.scrollLeft+=e.deltaY;}},{passive:false});track.addEventListener('keydown',e=>{let d={'ArrowRight':144,'ArrowLeft':-144,'PageDown':500,'PageUp':-500}[e.key];if(d){e.preventDefault();track.scrollLeft+=d;}if(e.key==='Home')track.scrollLeft=0;if(e.key==='End')track.scrollLeft=track.scrollWidth;});}}
function home(){const roster=Object.values(state.slots).map(pirate);return title('YOUR NEXT CHAPTER','A captain’s work is never done.','Season of the Drowned Crown')+'<section class="hero"><iframe class="hero-sea" src="/public/water.html" title="Animated ocean" tabindex="-1"></iframe><div class="hero-shade"></div><iframe id="homeShip" class="hero-ship" src="/public/ship.html?side=home" title="Your pirate ship" tabindex="-1"></iframe><div class="hero-stamp">THE OPEN SEA AWAITS</div><div class="hero-copy"><span class="pill green">⚓ '+M.PORTS[state.port]+' waters</span><h1>MAKE WAVES.<br><span class="gold">TAKE EVERYTHING.</span></h1><p>Your crew is ready. Pick a rival, find the weak spot, and send a message they won’t forget.</p><div class="hero-action">'+button(state.battle&&state.battle.phase!=='result'?'RESUME BATTLE →':'SET SAIL →','start','','primary')+'<small>Two ships. One survivor.<br>Local battles · seeded rivals</small></div></div></section><div class="dashboard-grid"><section class="card"><div class="row between"><div class="mini-heading">Your fighting crew</div>'+button('Manage →','nav','crew','ghost small')+'</div><div class="crew-dots">'+roster.map(p=>'<div class="crew-dot" title="'+p.name+'">'+p.icon+'</div>').join('')+'</div><p class="footer-note">'+roster.length+' gunners aboard · Ship level '+state.shipLevel+' · '+M.FINISHERS[state.move].name+'</p></section><section class="card"><div class="row between"><div class="mini-heading">Captain’s orders</div><span class="pill">DAILY</span></div><div class="quest"><div class="row between"><span>Finish 3 battles</span><span>'+Math.min(3,state.quests.matches)+'/3</span></div><progress max="3" value="'+state.quests.matches+'"></progress>'+button(state.quests.dailyClaim?'Collected ✓':'Claim 100 season XP','quest','daily','ghost small',state.quests.dailyClaim||state.quests.matches<3)+'</div></section><section class="card"><div class="row between"><div class="mini-heading">Your season</div><span class="gold">✦</span></div><div class="row spaced"><span class="mini-number">'+M.seasonLevel(state)+'</span><div><strong>Pirate’s Booty</strong><p style="font-size:11px">'+(state.xp%100)+' / 100 XP to next level</p></div></div><progress max="100" value="'+state.xp%100+'"></progress>'+button('See your rewards →','nav','booty','ghost small')+'</section></div><section class="card spaced"><div class="row between"><div><div class="eyebrow">THE HOLD</div><h3>Your hard-earned haul</h3></div><small>'+state.dailyChests+' / 5 chest drops today</small></div><div class="chests spaced">'+Array.from({length:5},(_,i)=>{const c=state.chests[i];return c?button('<span>🧰</span><strong>'+c.kind+'</strong><small>Open chest</small>','chest',c.id,'chest'): '<div class="chest muted" style="border:1px dashed var(--line);border-radius:10px"><span>▱</span><small>Win a battle</small></div>';}).join('')+'</div></section>';}
function card(p){const owned=state.levels[p.id]>0,posted=Object.values(state.slots).includes(p.id);return '<button class="pirate-card '+(selected===p.id?'selected ':'')+(!owned?'locked':'')+'" style="--rarity:var(--'+p.rarity+')" data-action="'+(tab==='ship'&&owned?'select':'detail')+'" data-id="'+p.id+'">'+(posted?'<span class="posted">ON SHIP</span>':'')+art(p)+'<span class="rarity">'+p.rarity+'</span><strong class="name">'+p.name+'</strong><small>'+(owned?'Lv. '+state.levels[p.id]+' · '+p.primary:'Found in chests')+'</small></button>';}
function crew(){return title('ALL HANDS ON DECK','The right crew. The wrong crowd.','36 pirates. A thousand ways to fight.')+'<div class="tabs">'+[['ship','Ship'],['collection','Collection'],['yard','Shipyard'],['equipment','Equipment']].map(([k,n])=>button(n,'tab',k,tab===k?'active':'')).join('')+'</div>'+(tab==='ship'?'<div class="split"><section class="card"><div class="row between"><h3>The Blackwake</h3><span class="pill">LEVEL '+state.shipLevel+'</span></div>'+diagram()+'<p style="font-size:12px">'+(selected?'Posting '+pirate(selected).name+'. Choose an open station.':'Select a pirate, then a station. Tap a filled station to stand them down.')+'</p><div class="row spaced">'+button('Cancel selection','unselect','','ghost small',!selected)+(selected?button('View pirate','detail',selected,'small'):'')+'</div><p class="footer-note">● Deck: exposed, clear line of fire<br>● Gun ports: protected by the hull</p></section><section><div class="row between" style="margin-bottom:14px"><h3>Your crew</h3><small>'+M.PIRATES.filter(p=>state.levels[p.id]).length+' / 36 recruited</small></div><div class="roster scroll-panel">'+M.PIRATES.filter(p=>state.levels[p.id]).map(card).join('')+'</div></section></div>':tab==='collection'?'<div class="roster">'+M.PIRATES.map(card).join('')+'</div>':tab==='yard'?yard():equipment());}
function diagram(){const valid=M.positions(state);return '<div class="ship-diagram"><div class="mast"></div><div class="sail-drawing">☠</div><div class="ship-outline"></div>'+['d0','d1','d2','d3','h0','h1','h2','h3'].map((key,i)=>{const p=state.slots[key]&&pirate(state.slots[key]),open=valid.includes(key);return '<button class="slot '+(i>3?'port ':'')+(!open?'locked':'')+'" style="left:'+(24+i%4*17)+'%;top:'+(i<4?43:66)+'%" data-action="slot" data-id="'+key+'" aria-label="'+(open?(p?p.name:'Empty')+' '+(i<4?'deck':'gun port')+' station '+(i%4+1):'Locked station')+'" '+(!open?'disabled':'')+'>'+(open?p?p.icon:'+':'⌑')+'</button>';}).join('')+'</div>';}
function yard(){const c=state.shipLevel<8?{...M.E.SHIP[state.shipLevel-1]}:null;return '<div class="split"><section class="card"><div class="eyebrow">SHIPWRIGHT’S YARD</div><h2 class="spaced">Room for one more troublemaker.</h2>'+diagram()+materials()+'<div class="rule"></div><p>Each ship level opens one new gun station. Your current crew stays aboard.</p><div class="row spaced">'+button(c?'Upgrade to level '+(state.shipLevel+1):'Fully upgraded','ship-up','','primary',!c)+'</div><p class="footer-note">'+(c?cost(c):'Eight stations. A formidable ship.')+'</p></section><section class="card"><h3>The gunsmith</h3><p class="spaced">Cards buy experience. Gold pays the gunsmith. Great weapons take a little time.</p>'+bench()+'<div class="rule"></div><h3>The position ladder</h3>'+Object.entries(M.LADDER).map(([l,[d,h]])=>'<div class="row between" style="padding:10px 0;border-bottom:1px solid var(--line)"><span>Level '+l+'</span><small>'+d+' deck · '+h+' hull</small><strong>'+(+l<=state.shipLevel?'✓':'⌑')+'</strong></div>').join('')+'</section></div>';}
function bench(){if(!state.bench)return '<div class="empty spaced">Your bench is free.<br><small>Open a crew card to start an upgrade.</small></div>';const b=state.bench,left=Math.max(0,b.ends-Date.now()),gems=Math.ceil(left/360000);return '<div class="card spaced"><h3>'+pirate(b.id).name+'</h3><p data-timer="'+b.ends+'">'+duration(left)+' remaining</p>'+button('Finish now · 💎 '+gems,'skip','','primary small')+'</div>';}
function equipment(){
const rc=M.repairCost(state);
return materials()+'<div class="row between spaced"><h3>Protection that earns its scars.</h3>'+button('Repair · '+(Object.keys(rc).length?cost(rc):'Ready'),'repair','','small',!Object.keys(rc).length)+'</div><p class="footer-note">Each hull section has its own plating and condition. Worn equipment never blocks battle.</p><div class="gear-grid spaced">'+state.plates.slice(0,state.shipLevel).map((p,i)=>'<section class="card"><div class="eyebrow">HULL SECTION '+(i+1)+'</div><h3>'+p.kind+'</h3><p>'+Math.round(p.durability)+'% condition</p>'+button('Hardwood · 220 wood + 1,800 gold','equip','plating:hardwood:'+i,'small',p.kind==='hardwood')+button('Iron · 140 metal + 3,000 gold + 25 gems','equip','plating:iron:'+i,'small spaced',p.kind==='iron')+'</section>').join('')+'</div><h3 class="spaced">Canvas · '+Math.round(state.canvasDurability)+'% condition</h3><div class="gear-grid spaced">'+[['heavy','Heavy canvas','20% protection','180 cloth · 1,200 gold'],['storm','Storm canvas','30% protection','240 cloth · 2,400 gold · 20 gems']].map(([v,n,desc,c])=>'<section class="card"><h3>'+n+'</h3><p>'+desc+'</p><small>'+c+'</small>'+button(state.canvas===v?'Fitted ✓':'Fit canvas','equip','canvas:'+v,'small spaced',state.canvas===v)+'</section>').join('')+'</div><h3 class="spaced">Permanent enhancements</h3><div class="gear-grid spaced">'+Object.entries(M.E.ENHANCEMENTS).map(([n,v])=>{const l=state.enh[n]||0;return '<div class="card"><h3>'+n+'</h3><p>'+v.effect+' · Grade '+l+'/5</p>'+button(l===5?'Maxed':'Improve · '+cost({gold:M.E.ENH_GOLD[l],gems:M.E.ENH_GEMS[l]}),'enhance',n,'small',l===5)+'</div>';}).join('')+'</div><h3 class="spaced">A face for your ship</h3><div class="gear-grid spaced">'+M.E.FIGUREHEADS.map((f,i)=>{const l=state.figureheads[i]||0;return '<div class="card"><div class="gear-icon">'+['🐕','🐏','🐢','🦅','🐙','🐉'][i]+'</div><h3>'+f.name+'</h3><p>'+f.bias+' · Grade '+l+'/4</p><small>'+(!l?cost({gold:f.gold,gems:f.gems}):'Permanently owned')+'</small><div class="spaced">'+button(state.figurehead===i?'Equipped ✓':l?'Equip':'Acquire','figure',i,'small',state.figurehead===i)+(l&&l<4?button('Improve · '+cost({gold:M.E.FIG_UPGRADE.gold[l-1],gems:M.E.FIG_UPGRADE.gems[l-1]}),'figure-up',i,'small spaced'):'')+'</div></div>';}).join('')+'</div><h3 class="spaced">Sails with personality</h3><div class="gear-grid spaced">'+M.E.SAILS.map((v,i)=>'<div class="card"><div class="gear-icon">'+['☠','⚓','⚔','✦','☽','♛'][i]+'</div><h3>'+['Jolly Roger','Anchor','Crossed Blades','Morning Star','Moonwake','Royal Fortune'][i]+'</h3><p>Cosmetic · gold only</p>'+button(state.cosmetic===i?'Equipped ✓':state.cosmetics.includes(i)?'Equip':fmt(v)+' gold','cosmetic',i,'small',state.cosmetic===i)+'</div>').join('')+'</div>';
}
function detail(id){const p=pirate(id),l=state.levels[id],st=M.stats(p,l||1),c=M.upgradeCost(state,id);modal('<div class="eyebrow">'+p.rarity+' · '+(l?'LEVEL '+l:'UNRECRUITED')+'</div>'+art(p,'detail-portrait')+'<h2>'+p.name+'</h2><p>'+p.projectile+'</p><div class="badge-row">'+p.tags.map(t=>'<span class="pill">'+t+'</span>').join('')+'</div><div class="stats">'+Object.entries(st).map(([k,v])=>'<div class="stat"><small>'+k.toUpperCase()+'</small><strong>'+v+'</strong></div>').join('')+'</div><p>'+(!l?'Win chests to recruit this pirate. Each card belongs to a specific crew member.':c?'Next upgrade: '+c.cards+' cards and '+fmt(c.gold)+' gold. Bench time '+duration(c.hours*3600000)+'.':'This pirate has reached level 12.')+'</p><p class="spaced">Cards held: <strong>'+state.cards[id]+'</strong></p><div class="row spaced">'+button('Start upgrade','upgrade',id,'primary',!c||!!state.bench||state.cards[id]<c.cards||state.gold<c.gold)+(l?button('Select for ship','select-detail',id,'ghost'):'')+'</div>'+bench());}
const coords=[[-.13,51.51],[1.86,50.95],[-9.14,38.72],[-64.78,32.31],[-66.59,18.22],[-66.88,10.49],[-122.33,47.61],[-157.86,21.31],[120.98,14.60],[103.82,1.35],[114.17,22.32],[121.47,31.23],[72.88,19.08],[39.67,-4.04],[47.51,-18.88]];
const land=[[[-168,66],[-140,70],[-95,70],[-80,62],[-64,60],[-52,47],[-66,45],[-75,35],[-81,25],[-97,26],[-105,20],[-115,30],[-125,40],[-130,55],[-150,60]],[[-81,8],[-60,10],[-50,0],[-35,-5],[-38,-22],[-48,-25],[-58,-35],[-62,-42],[-70,-52],[-75,-45],[-72,-30],[-70,-18],[-78,-5]],[[-10,36],[0,45],[-2,49],[2,51],[8,54],[10,58],[20,60],[30,60],[40,45],[36,36],[33,31],[43,12],[51,12],[40,-5],[40,-25],[25,-34],[18,-34],[12,-18],[9,4],[-5,5],[-17,15],[-16,28]],[[30,60],[60,70],[100,75],[140,72],[160,60],[140,50],[130,42],[122,30],[110,20],[105,10],[100,5],[95,15],[88,22],[80,10],[72,20],[60,25],[50,28],[43,12],[40,45]],[[113,-22],[130,-12],[142,-11],[150,-25],[153,-28],[147,-38],[135,-35],[125,-33],[115,-34]]];
const xy=([lon,lat])=>[(lon+180)*2,(90-lat)*2];
function ports(){const rows=M.board(state,port);return title('A WORLD WORTH PLUNDERING','Every port has a story.','Weekly wins decide your place. Trophies break the tie.')+'<div class="port-list">'+M.PORTS.map((n,i)=>button(n,'port',i,port===i?'active':'')).join('')+'</div><div class="ports-layout"><div class="chart"><svg class="map-svg" viewBox="0 0 720 360" role="img" aria-label="World chart of fifteen ports">'+land.map(pts=>'<path class="land" d="M'+pts.map(p=>xy(p).join(',')).join('L')+'Z"/>').join('')+'<path class="route" d="M'+coords.map(p=>xy(p).join(',')).join('L')+'"/>'+coords.map((p,i)=>'<g class="map-pin '+(port===i?'selected':'')+'" data-action="port" data-id="'+i+'"><circle cx="'+xy(p)[0]+'" cy="'+xy(p)[1]+'" r="'+(port===i?7:4)+'"/><title>'+M.PORTS[i]+'</title></g>').join('')+'</svg><div class="compass">✧<small style="font-size:10px;display:block">N</small></div></div><section class="card"><div class="eyebrow">PORT '+(port+1)+'/15</div><h2 class="spaced">'+M.PORTS[port]+'</h2><div class="port-fact"><strong>'+('★'.repeat(1+Math.floor(port/3)))+'</strong><small>DIFFICULTY</small></div><div class="port-fact"><strong>100</strong><small>CAPTAINS · BOARD I</small></div><div class="port-fact"><strong class="foam">Top 10 ↑</strong><small>SAIL TO THE NEXT PORT</small></div><div class="port-fact"><strong>Bottom 10 ↓</strong><small>RETURN TO THE LAST PORT</small></div><p class="footer-note">Settles Monday, 00:00 UTC.<br>Seeded rivals · local standings.</p></section><section class="card" style="padding:8px"><div class="board"><div class="board-row board-head"><span>#</span><span>CAPTAIN</span><span>WINS</span><span>🏆</span></div>'+rows.map((p,i)=>'<button class="board-row '+(p.self?'self ':i<10?'promote ':i>89?'demote ':'')+'" data-action="captain" data-id="'+i+'"><strong>'+(i+1)+'</strong><span>'+esc(p.name)+(p.self?' · YOU':'')+'</span><strong>'+p.wins+'</strong><span>'+p.trophies+'</span></button>').join('')+'</div></section></div>';}
function booty(){return title('PIRATE’S BOOTY','The sea rewards the bold.','Captain’s share above. Crew’s share below.')+'<div class="season-intro"><div class="row"><span class="mini-number gold">'+M.seasonLevel(state)+'</span><div><h3>Season of the Drowned Crown</h3><p>'+Math.max(1,Math.ceil(((state.season+1)*28*86400000-Date.now())/86400000))+' days remaining · '+state.xp+' season XP</p></div></div><div class="row">'+button('Claim all available','claim-all','','primary')+button('Finishing moves','moves','','ghost')+'</div></div><p style="font-size:11px">'+(state.premium?'CAPTAIN’S SHARE · LOCAL PREVIEW':'CAPTAIN’S SHARE · Preview available in Settings; real purchases not connected')+'</p><div class="season-track" id="track" tabindex="0" aria-label="Season rewards; use arrow keys to scroll">'+Array.from({length:50},(_,i)=>{const l=i+1;return '<div class="reward-column '+([6,14,22,30,38,46].includes(l)?'wide':'')+'">'+reward(l,true)+'<div class="waypoint '+(l===M.seasonLevel(state)?'current':'')+'"><span>'+l+'</span></div>'+reward(l,false)+'</div>';}).join('')+'</div><p style="font-size:11px" class="foam">CREW’S SHARE · FREE FOR EVERY CAPTAIN</p><div class="card spaced row between"><div><h3>Weekly orders</h3><p>Win 5 battles · '+Math.min(5,state.quests.wins)+'/5</p></div>'+button(state.quests.weeklyClaim?'Claimed ✓':'Claim 300 XP','quest','weekly','small',state.quests.weeklyClaim||state.quests.wins<5)+'</div>';}
function reward(l,prem){const r=M.rewardAt(l,prem),claimed=state.claims.includes(l+':'+prem),ready=l<=M.seasonLevel(state)&&(!prem||state.premium)&&!claimed;const move='move'in r?M.FINISHERS[r.move]:null;return '<button class="reward '+(prem?'premium ':'')+(ready?'ready ':'')+(claimed?'claimed':'')+'" data-action="claim" data-id="'+l+':'+prem+'" '+(!ready?'disabled':'')+'><span class="reward-art">'+(move?move.icon:r.gems?'💎':'🪙')+'</span><strong class="label">'+(move?move.name:r.gems?r.gems+' gems':r.gold+' gold')+'</strong><small>'+(claimed?'CLAIMED ✓':ready?'CLAIM REWARD':prem&&!state.premium?'CAPTAIN’S SHARE ⌑':'LEVEL '+l)+'</small></button>';}
function moves(){modal('<div class="eyebrow">THE DEEP ANSWERS YOUR CALL</div><h2>Make it a spectacle.</h2><p>Land both shots four turns in a row. One finishing move per match.</p><div class="gear-grid spaced">'+M.FINISHERS.map(m=>'<div class="card"><div class="gear-icon">'+m.icon+'</div><h3>'+m.name+'</h3><p>'+m.hits+'</p>'+button(state.move===m.id?'Equipped ✓':state.moves.includes(m.id)?'Equip':'💎 '+m.gems,'move',m.id,'small',state.move===m.id)+'</div>').join('')+'</div>');}
function store(){const deals=M.offers(state);save();return title('THE CAPTAIN’S MARKET','A little edge. A lot of character.','Gold is earned. Glory is taken.')+'<div class="store-layout"><aside class="deals"><div class="eyebrow" style="margin-bottom:12px">FOR YOUR VOYAGE</div>'+deals.map(o=>{const b=M.E.BUNDLES[o.bundle];return '<section class="card" data-offer="'+o.key+'"><h3>'+b.name+'</h3><p>'+fmt(b.gems)+' gems · '+fmt(b.gold)+' gold</p><small>'+b.mats+' materials · '+b.cards+' cards · '+Math.round(b.discount*100)+'% catalog saving</small><p data-timer="'+o.ends+'">'+duration(o.ends-Date.now())+' remaining</p>'+button('$'+b.price.toFixed(2)+' · Not connected','purchase','','small',true)+button('No thanks','decline',o.key,'ghost small')+'</section>';}).join('')+'<section class="card"><div class="gear-icon">⚓</div><h3>A ship worth fearing.</h3><p>Put your spoils to work. Upgrade the hull, fit a figurehead, or fly your own colors.</p>'+button('Visit the shipyard →','yard','','small')+'</section><section class="card"><h3>The deep is listening.</h3><p>Earn gems from new ports and chest runs. Unlock finishing moves without buying a pass.</p>'+button('Choose a finishing move','moves','','small')+'</section><p class="footer-note">Real-money purchases are not connected in this local voyage. No payment is taken.</p></aside><div><section class="card"><div class="row between"><div><div class="eyebrow">TRADE SHOP</div><h3>Someone else’s surplus. Your next upgrade.</h3></div></div><div class="spaced">'+materials()+'</div><div class="row wrap spaced"><label>Give <select id="tradeFrom"><option>wood</option><option>metal</option><option>cloth</option></select></label><label>Receive <select id="tradeTo"><option>metal</option><option>wood</option><option>cloth</option></select></label>'+button('Exchange 10 units','trade','','primary small')+'</div><p class="footer-note">12 gold per received unit, plus materials at the port rate. Available stock: '+Object.entries(state.stock).map(([k,v])=>v+' '+k).join(' · ')+'</p></section><h3 class="spaced">Gem packs</h3><div class="pack-grid spaced">'+M.E.PACKS.map((p,i)=>'<section class="card"><div class="gear-icon">'+['💎','👝','🧰','📦','🏴‍☠️','👑'][i]+'</div><h3>'+p.name+'</h3><div class="mini-number foam">'+fmt(p.gems)+'</div><small>gems</small>'+button('$'+p.price.toFixed(2)+' · Not connected','purchase',i,'ghost',true)+'</section>').join('')+'</div><h3 class="spaced">A captain’s provisions</h3><div class="pack-grid spaced">'+M.E.BUNDLES.map((p,i)=>'<section class="card"><div class="gear-icon">🎁</div><h3>'+p.name+'</h3><p>'+fmt(p.gems)+' gems · '+fmt(p.gold)+' gold</p><small>'+p.mats+' materials · '+p.cards+' cards</small>'+button('$'+p.price.toFixed(2)+' · Not connected','purchase',i,'ghost',true)+'</section>').join('')+'</div></div></div>';}
function settings(){return title('CAPTAIN’S QUARTERS','Make yourself at home.','This voyage is saved in this browser.')+'<div class="settings-grid"><section class="card setting"><div><h3>Captain’s name</h3><p>How you appear on your port board.</p></div><input id="captainName" maxlength="24" aria-label="Captain name" value="'+esc(state.name)+'"></section><section class="card setting"><div><h3>Sound</h3><p>Cannon fire and victory cues.</p></div>'+button(state.settings.sound?'On':'Off','setting','sound','small')+'</section><section class="card setting"><div><h3>Motion and effects</h3><p>Reduce screen shake and transitions.</p></div>'+button(state.settings.motion?'Full motion':'Reduced','setting','motion','small')+'</section><section class="card setting"><div><h3>Captain’s share preview</h3><p>Try the paid reward track locally. This is a preview, not a purchase.</p></div>'+button(state.premium?'Preview on':'Enable preview','preview','','small')+'</section><section class="card"><h3>Keep your captain close.</h3><p class="spaced">Export a backup before changing browsers. Import restores a valid exported captain; this does not connect a shared account.</p><div class="row wrap spaced">'+button('Export captain','export','','small')+'<label class="pill" style="min-height:44px;cursor:pointer">Import backup<input type="file" id="importSave" accept=".json" style="max-width:160px"></label>'+button('How to play','help','','ghost small')+'</div></section><p class="footer-note">Starting supplies: 1,800 gold, 40 gems, three ship stations and four recruited pirates. Seeded rivals and all progress are local. Weekly settlement uses UTC; season length is 28 days. Source prototypes preserved in Code Prototypes.</p></div>';}
function arena(){const b=state.battle;if(!b){page='battle';return home();}return '<section class="arena"><iframe class="arena-water" src="/public/water.html" title="Battle ocean" tabindex="-1"></iframe><div class="battle-top"><div class="health-card"><div class="eyebrow">YOUR SHIP</div><h3>'+esc(state.name)+'’s Blackwake</h3><progress id="playerHealth" max="'+b.player.maxHull+'" value="'+b.player.hull+'"></progress><div class="health-meta" id="playerMeta"></div></div><div class="turn"><small id="phaseLabel">YOUR TURN</small><div class="display" id="turnLabel">TURN '+b.turn+'</div><div id="shots"></div><small id="turnClock" aria-label="Turn time remaining"></small></div><div class="health-card enemy"><div class="eyebrow">RIVAL CAPTAIN</div><h3>'+esc(b.enemyName)+'</h3><progress id="enemyHealth" max="'+b.enemy.maxHull+'" value="'+b.enemy.hull+'"></progress><div class="health-meta" id="enemyMeta"></div></div></div><iframe class="battle-ship player" id="playerShip" src="/public/ship.html?side=player" title="Your ship" tabindex="-1"></iframe><iframe class="battle-ship enemy" id="enemyShip" src="/public/ship.html?side=enemy" title="Enemy ship: aim by clicking hull, crew or sails"></iframe><div class="battle-center">⚔<br><span id="aimHint">AIM AT THE ENEMY SHIP</span></div><div class="battle-log" id="battleLog" role="status"></div><div class="battle-bottom"><div><div class="eyebrow" style="margin-bottom:8px">CHOOSE YOUR GUNNER</div><div class="gun-selection" id="guns"></div></div><div class="stack" style="gap:6px"><div class="target-buttons">'+['hull','sails','crew'].map(t=>button(t.toUpperCase(),'target',t,'small target-'+t)).join('')+'</div>'+button('FIRE AT TARGET','fire','','primary')+'</div><div class="stack" style="gap:6px">'+button('🔭 Telescope','scope','','small')+button('Finishing move','finisher','','finisher')+'</div><div>'+button('Retreat','retreat','','ghost small')+'</div></div></section>';}
function send(side,data){const f=el(side+'Ship');f?.contentWindow?.postMessage({type:'pirate-render',...data},location.origin);}
function visualCrew(f){return f.crew.map(g=>({...g,name:pirate(g.id).name,type:{hull:0,crew:1,sails:2}[pirate(g.id).primary]}));}
function configure(side){if(side==='home'){send(side,{action:'configure',level:state.shipLevel,count:Object.keys(state.slots).length,crew:Object.entries(state.slots).map(([slot,id])=>({slot,id,hp:1,name:pirate(id).name})),cosmetic:state.cosmetic,motion:state.settings.motion});return;}const b=state.battle;if(!b)return;send(side,{action:'configure',level:state.shipLevel,count:M.active(b[side]).length,crew:visualCrew(b[side]),cosmetic:side==='player'?state.cosmetic:null,motion:state.settings.motion});for(const e of b.events)if(e.hit&&e.side!==(side))send(side,{action:'hit',x:e.x,y:e.target==='sails'?1.2:e.target==='crew'?.4:e.y,weapon:e.weapon});}
function updateArena(){const b=state.battle;if(!b||!el('playerHealth'))return;for(const side of ['player','enemy']){send(side,{action:'sync',crew:visualCrew(b[side])});el(side+'Health').value=b[side].hull;el(side+'Meta').innerHTML='<span>'+Math.ceil(b[side].hull)+' HULL</span><span>'+Math.round(b[side].sails)+'% SAILS</span><span>'+M.active(b[side]).length+' CREW</span>';}el('turnLabel').textContent='TURN '+b.turn;el('phaseLabel').textContent=b.phase==='player'?'YOUR TURN':b.phase==='result'?'BATTLE OVER':'ENEMY TURN';el('turnClock').textContent=b.phase==='player'?Math.ceil(b.seconds??30)+'s'+(busy?' · PAUSED':''):'';el('shots').innerHTML=[0,1].map(i=>'<i class="shot-dot '+(i>=b.shots?'spent':'')+'"></i>').join('');if(!M.active(b.player).some(g=>g.id===gunner))gunner=M.active(b.player)[0]?.id;el('guns').innerHTML=M.active(b.player).map(g=>{const p=pirate(g.id);return button('<span>'+p.icon+'</span><small>'+p.name+'</small>','gun',g.id,gunner===g.id?'active':'',busy);}).join('');document.querySelectorAll('[data-action=target]').forEach(e=>e.classList.toggle('active',e.dataset.id===target));document.querySelector('[data-action=fire]').disabled=busy||b.phase!=='player';const f=document.querySelector('[data-action=finisher]');f.disabled=busy||!b.charged||b.used||b.phase!=='player';f.classList.toggle('charged',b.charged);f.innerHTML=M.FINISHERS[state.move].icon+' '+(b.charged?'UNLEASH!':b.used?'MOVE USED':b.streak+'/4 DUAL HITS');el('battleLog').textContent=b.log.at(-1)||'Choose a gunner. Aim for their strongest target.';save();}
function sound(freq=120,length=.15){if(!state.settings.sound)return;try{const a=audioContext||(audioContext=new AudioContext()),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.type='triangle';o.frequency.setValueAtTime(freq,a.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(25,freq/4),a.currentTime+length);g.gain.setValueAtTime(.1,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+length);o.start();o.stop(a.currentTime+length);}catch{}}
let audioContext;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function showEvent(e){if(!e)return;send(e.side,{action:'fire',gunner:e.gunnerId});sound(e.hit?140:80,.25);const a=document.querySelector('.arena');if(a&&state.settings.motion){const p=document.createElement('i');p.className='projectile '+(e.side==='enemy'?'reverse':'');a.append(p);setTimeout(()=>p.remove(),600);}await sleep(state.settings.motion?450:80);if(e.hit)send(e.side==='player'?'enemy':'player',{action:'hit',x:e.x||0,y:e.target==='sails'?1.2:e.target==='crew'?.4:e.y||0,weapon:e.weapon});updateArena();}
async function fire(x=0,y=0){if(busy||!state.battle||state.battle.phase!=='player')return;busy=true;const e=M.attack(state,{gunner,target,x,y});updateArena();await showEvent(e);if(state.battle.phase==='result'){busy=false;finish();return;}if(state.battle.phase==='enemy'){await sleep(400);const events=M.enemyTurn(state);for(const e of events)await showEvent(e);}busy=false;updateArena();if(state.battle.phase==='result')finish();}
function finish(){M.settle(state);save();const r=state.lastResult;if(!r)return;sound(r.won?640:160,.5);modal('<div class="eyebrow">'+(r.won?'THE SEA IS YOURS':'LIVE TO FIGHT ANOTHER DAY')+'</div><div class="dialog-art">'+(r.won?'🏴‍☠️':'⚓')+'</div><h2 class="result-title">'+(r.won?'VICTORY!':'OUTGUNNED.')+'</h2><p>'+esc(r.enemyName)+(r.won?' has struck their colors. Your crew has earned its share.':' won this broadside. Study the damage and make the next shots count.')+'</p><div class="reward-summary"><div class="card"><h3 class="gold">+'+r.gold+'</h3><small>GOLD EARNED</small></div><div class="card"><h3 class="foam">+'+(r.won?50:20)+'</h3><small>SEASON XP</small></div><div class="card"><h3>'+(r.chest?'🧰':'—')+'</h3><small>'+(r.chest?r.chest.kind.toUpperCase()+' CHEST':'NO CHEST DROP')+'</small></div></div>'+(!r.won?'<p><strong>What you learned</strong><br>'+r.log.slice(-3).map(esc).join('<br>')+'</p>':'')+'<div class="row wrap spaced">'+(!r.won&&!r.rematch&&!r.rematchAsked?button('Demand a rematch','rematch','','primary'):'')+button('Return to port →','return','',''+(r.won?'primary':'ghost'))+'</div>');}
let cinemaResolve=null;
async function finisher(){
if(busy)return;const move=M.finishMove(state);if(!move)return;
busy=true;const repeat=(state.seenMoves||[]).includes(move.id);state.seenMoves??=[];if(!repeat)state.seenMoves.push(move.id);save();
const c=el('cinema');c.innerHTML='<div class="poster"><div class="eyebrow">A PIRATE CLASHERS PICTURE</div><div class="beast">'+move.icon+'</div><h1>'+move.name.toUpperCase()+'</h1><p>ALL HANDS. BRACE YOURSELVES.</p>'+button('Skip spectacle','skip-cinema','','ghost spaced')+'</div>';
c.hidden=false;sound(300,.8);let skipped=false;
await Promise.race([sleep(state.settings.motion?(repeat?500:1400):100),new Promise(r=>cinemaResolve=()=>{skipped=true;r();})]);
send('enemy',{action:'finisher',id:move.id});
if(!skipped)await Promise.race([sleep(state.settings.motion?900:100),new Promise(r=>cinemaResolve=r)]);
cinemaResolve=null;c.hidden=true;busy=false;sound(650,.3);updateArena();if(state.battle.phase==='result')finish();
}

function help(){modal('<div class="eyebrow">WELCOME ABOARD</div><h2>Your ship. Your shots. Your spoils.</h2><p><strong>1. Post your crew.</strong> Select a pirate and tap an open station. Deck gunners are exposed; hull gunners get cover.</p><p class="spaced"><strong>2. Pick your shots.</strong> In battle, choose a gunner and click the enemy hull, sails or crew. You have two shots each turn. The target buttons and Fire work with a keyboard too.</p><p class="spaced"><strong>3. Make a scene.</strong> Hit both shots four turns running to charge your equipped finishing move.</p><p class="spaced"><strong>4. Bring home the booty.</strong> Wins earn chests. Cards and gold upgrade your crew. Weekly wins move you through ports.</p><div class="row spaced">'+button('Aye, captain →','onboard','','primary')+'</div>');}
function actionResult(ok,msg){if(!ok)toast('Not enough supplies, or this action is not available yet.');else{save();toast(msg);render();}}
document.addEventListener('click',async ev=>{const b=ev.target.closest('[data-action]');if(!b||b.disabled)return;const {action:a,id}=b.dataset;switch(a){
case 'nav':page=id;render();break;
case 'close':close();if(page==='arena'&&state.battle?.phase==='result'){page='battle';state.battle=null;save();render();}break;
case 'tab':tab=id;render();break;
case 'yard':page='crew';tab='yard';render();break;
case 'select':selected=Number(id);render();break;
case 'select-detail':selected=Number(id);close();page='crew';tab='ship';render();break;
case 'unselect':selected=null;render();break;
case 'slot':if(selected){M.assign(state,selected,id);selected=null;}else delete state.slots[id];save();render();break;
case 'detail':detail(Number(id));break;
case 'upgrade':if(M.upgrade(state,Number(id))){save();close();toast('The gunsmith is on the job.');render();}else toast('Check your cards, gold, and bench.');break;
case 'skip':actionResult(M.skip(state),'Upgrade complete.');close();break;
case 'ship-up':actionResult(M.shipUpgrade(state),'A new gun station is ready.');break;
case 'equip':{const[k,v,i]=id.split(':');actionResult(M.equip(state,k,v,Number(i||0)),'Fitted and ready.');break;}
case 'repair':actionResult(M.repair(state),'Ready for another broadside.');break;
case 'enhance':actionResult(M.enhance(state,id),'Enhancement installed.');break;
case 'figure-up':actionResult(M.upgradeFigure(state,Number(id)),'Figurehead upgraded.');break;
case 'figure':actionResult(M.figure(state,Number(id)),'Figurehead fitted.');break;
case 'cosmetic':actionResult(M.cosmetic(state,Number(id)),'Flying your colors.');break;
case 'quest':actionResult(M.questClaim(state,id),'Season XP claimed.');break;
case 'chest':{const r=M.openChest(state,id);if(!r)break;save();render();modal('<div class="eyebrow">A FAIR SHARE OF THE SPOILS</div><div class="dialog-art">🧰</div><h2>Look what the tide brought in.</h2><p class="gold">+'+r.gold+' gold</p><div class="roster spaced">'+Object.entries(r.cards).map(([id,n])=>'<div class="card"><div class="pirate-icon">'+pirate(id).icon+'</div><strong>'+pirate(id).name+'</strong><p>+'+n+' card'+(n>1?'s':'')+'</p></div>').join('')+'</div>');break;}
case 'port':port=Number(id);render();break;
case 'captain':{const p=M.board(state,port)[Number(id)];modal('<div class="eyebrow">'+M.PORTS[port]+' · CAPTAIN’S RECORD</div><h2>'+esc(p.name)+'</h2><div class="stats"><div class="stat"><small>SHIP LEVEL</small><strong>'+p.level+'</strong></div><div class="stat"><small>WEEKLY WINS</small><strong>'+p.wins+'</strong></div><div class="stat"><small>TROPHIES</small><strong>'+p.trophies+'</strong></div></div><p>'+(p.self?'Your place in these waters.':'A seeded rival captain. Scout the enemy deck during battle to identify their gunners.')+'</p>');break;}
case 'claim':{const[l,p]=id.split(':');actionResult(M.claim(state,Number(l),p==='true'),'Reward claimed.');break;}
case 'claim-all':{let n=0;for(let l=1;l<=M.seasonLevel(state);l++)for(const p of[false,true])if(M.claim(state,l,p))n++;save();render();toast(n?n+' rewards claimed.':'All available rewards already claimed.');break;}
case 'moves':moves();break;
case 'move':{const n=Number(id);if(state.moves.includes(n)||M.buyMove(state,n)){state.move=n;save();moves();}else toast('Earn more gems from port discoveries and chest runs.');break;}
case 'decline':M.declineOffer(state,id);save();render();break;
case 'trade':actionResult(M.exchange(state,el('tradeFrom').value,el('tradeTo').value),'Trade complete.');break;
case 'setting':state.settings[id]=!state.settings[id];save();render();break;
case 'preview':state.premium=!state.premium;save();render();toast('Local reward-track preview '+(state.premium?'enabled.':'disabled.'));break;
case 'export':{const blob=new Blob([saveError?localStorage.getItem(KEY)||JSON.stringify(state):JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pirate-captain.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);break;}
case 'help':help();break;
case 'onboard':state.onboarded=true;save();close();break;
case 'start':if(state.battle&&state.battle.phase!=='result'){page='arena';render();if(state.battle.phase==='enemy'){M.enemyTurn(state);updateArena();if(state.battle.phase==='result')finish();}break;}if(M.startBattle(state)){page='arena';gunner=null;save();render();}else toast('Post at least one pirate to your ship first.');break;
case 'gun':gunner=Number(id);updateArena();break;
case 'target':target=id;updateArena();break;
case 'fire':await fire(0,target==='sails'?1.2:target==='crew'?.4:0);break;
case 'skip-cinema':cinemaResolve?.();break;
case 'finisher':await finisher();break;
case 'scope':scope=!scope;send('enemy',{action:'scope',on:scope});toast(scope?'Deck gunners are visible. Port gunners reveal themselves when firing.':'Telescope lowered.');break;
case 'retreat':modal('<h2>Strike your colors?</h2><p>Retreat counts as a loss. Your crew still earns a little gold for the fight.</p><div class="row spaced">'+button('Retreat','confirm-retreat','','danger')+button('Keep fighting','close','','primary')+'</div>');break;
case 'confirm-retreat':state.battle.won=false;state.battle.phase='result';finish();break;
case 'return':close();state.battle=null;page='battle';save();render();break;
case 'rematch':{b.disabled=true;b.textContent='Waiting for their answer…';await sleep(1500);const r=M.requestRematch(state);save();if(r){close();page='arena';render();toast('Challenge accepted. Their accuracy is reduced 20%.');}else{modal('<div class="dialog-art">⛵</div><h2>RUNNING SCARED.</h2><p>'+esc(state.lastResult.enemyName)+' has decided the open sea looks safer. No rematch, no reward. Their pride is another matter.</p><div class="spaced">'+button('Back to port','return','','primary')+'</div>');}break;}
}});
document.addEventListener('change',async e=>{if(e.target.id==='captainName'){state.name=e.target.value.trim().slice(0,24)||'Captain';save();}if(e.target.id==='importSave'){const file=e.target.files[0];if(!file)return;try{const next=M.restore(await file.text());state=next;saveError='';save();render();toast('Captain restored.');}catch{toast('That file is not a valid captain backup. Nothing changed.');}}});
window.addEventListener('message',e=>{if(e.origin!==location.origin||!e.data)return;const d=e.data;if(d.type==='pirate-ready'&&['home','player','enemy'].includes(d.side)&&e.source===el(d.side+'Ship')?.contentWindow)configure(d.side);if(d.type==='pirate-aim'&&d.side==='enemy'&&e.source===el('enemyShip')?.contentWindow){const aim=M.aimedTarget(d.x,d.y);if(!aim){toast('Aim at the hull, crew, or sails.');return;}target=aim;fire(d.x,d.y);}});
document.addEventListener('keydown',e=>{if(page==='arena'&&!el('sheet').open&&e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();fire(0,target==='sails'?1.2:target==='crew'?.4:0);}});
setInterval(async()=>{if(page==='arena'&&!busy&&!document.hidden&&!el('sheet').open&&state.battle?.phase==='player'){const expired=M.elapse(state);updateArena();if(expired){busy=true;try{for(const e of M.enemyTurn(state))await showEvent(e);}finally{busy=false;updateArena();}if(state.battle.phase==='result')finish();}}const old=state.bench?.id,stamp=state.day+state.week+state.season,dealKeys=Object.keys(state.deals).join();M.offers(state);if(page==='store'&&dealKeys!==Object.keys(state.deals).join())render();M.advance(state,Date.now());if(stamp!==state.day+state.week+state.season){save();if(page!=='arena')render();}if(old&&!state.bench){save();if(page!=='arena')render();toast('Your gunner’s upgrade is complete.');}document.querySelectorAll('[data-timer]').forEach(n=>n.textContent=duration(Number(n.dataset.timer)-Date.now())+' remaining');},1000);
function duration(ms){const m=Math.max(0,Math.ceil(ms/60000));return m>=60?Math.floor(m/60)+'h '+m%60+'m':m+'m';}
render();if(!state.onboarded)setTimeout(help,500);
